### ISSUE TITLE
Optional preview Image

### ISSUE THREAD

**Issue by stephangrass** [sksksksk/skvideo#1]
Hi,
very nice extension!
It will be fine, if you can add an option to upload and use an custom preview image.

Stephan

**Comment by heisenbol** [comment]
the branch localimg should resolve this issue. But it needs more testing. Was more complicated that I originally thought. Feel free to try it out and let me know

**Comment by heisenbol** [comment]
v0.0.11 adds experimental support for custom preview images (and adds support for TYPO3 10.3)
