### ISSUE TITLE
"Es ist ein Fehler aufgetreten" (T3 11, skvideo 1.4.4)

### ISSUE THREAD

**Issue by asche76** [sksksksk/skvideo#10]
Hallo,
ich bekommen den Fehler in Bild 3, wenn ich versuche das video zu starten. Bis dahin läuft alles.
- in verschiedenen browsern getestet
- adblocker aus
- cookies gelöscht
- T3 backend php dump autoload und flush all caches getätigt
- einbinden von videos normal per html/iframe klappt einwandfrei

hat jemand eine idee?

![image](https://github.com/sksksksk/skvideo/assets/47745128/93532e74-a3c0-4a6b-b217-06d2b849358c)
![image](https://github.com/sksksksk/skvideo/assets/47745128/af2b01ff-4761-4c7f-a632-5a3a195d0a34)
![image](https://github.com/sksksksk/skvideo/assets/47745128/4bd64c14-8499-4291-82f8-d76c5788cfe6)

**Comment by heisenbol** [comment]
Does it also happen with other videos or only this specific one?
Could you send the video code so I can try it out?

**Comment by asche76** [comment]
all videos, doesn't matter which YT video / nocookie or normal even makes no difference. 
example code (grabbed from embed iframe code)
https://www.youtube-nocookie.com/embed/c5UbGEWbII4
whole YT site
https://www.youtube.com/watch?v=c5UbGEWbII4

![image](https://github.com/sksksksk/skvideo/assets/47745128/3158f5c4-e747-4e19-953e-989b46943b86)

**Comment by heisenbol** [comment]
hmmm.... I can't reproduce this on my installation. 
Can you tell me if this is a composer or a traditional installation?
And could you check the javascript console of the page for any errors and post them here?

**Comment by asche76** [comment]
strange, no error only this..
![image](https://github.com/sksksksk/skvideo/assets/47745128/d5df6fdb-843c-4f45-bbbb-31c8fccdb42d)

**Comment by asche76** [comment]
see a problem, the domain path ist doubled, but why?
![image](https://github.com/sksksksk/skvideo/assets/47745128/27d61d43-62cf-41b5-b773-ae0e1f2ce906)

**Comment by asche76** [comment]
the plugins settings seems right
![image](https://github.com/sksksksk/skvideo/assets/47745128/390853f8-6d8c-4181-a8af-b6c5cdf94d7c)

**Comment by asche76** [comment]
ok got it, only the video code is needed. :D
sorry for the issue.

**Comment by asche76** [comment]
ok got it, only the video code is needed. :D
sorry for the issue.
