### ISSUE TITLE
How can I modify a template in my sitepackage.

### ISSUE THREAD

**Issue by Hobokens** [sksksksk/skvideo#6]
Hi,
thanks a lot for the helpful extension v1.1. 
I want to modify the template 'Skvideofsc.html' in my sitepackage but I can't find any constants to set the new path. Do I miss something?
Regards
Hobokens

**Comment by heisenbol** [comment]
have a look at the bottom of the documentation. I've just added a relevant section. This refers to the just released version 1.1.1
