### ISSUE TITLE
Add custom class to sk-video-modal

### ISSUE THREAD

**Issue by CarstenHager** [sksksksk/skvideo#7]
Hello,

sorry my English is not good.

Is it possible that I can add my own CSS classes to the buttons "cancel" and "continue"?

I would like to adapt the modal box to Bootstrap.

```
class = "btn btn-danger cancel"
class = "btn btn-success continue" 
```

can you outsource the modal box in Fluid Template?

**Comment by heisenbol** [comment]
In version 1.2.0, two additional constants were added that allow you to add these classes
`plugin.tx_skvideo.settings.cancelbutton_additionalclass = btn`
`plugin.tx_skvideo.settings.continuebutton_additionalclass = btn danger`

**Comment by CarstenHager** [comment]
Thank you
