### ISSUE TITLE
Video with time indication

### ISSUE THREAD

**Issue by Hobokens** [sksksksk/skvideo#8]
Hello,
I have a video link with a time indication, so that when it starts it jumps right to the right place. When the video is displayed after the user agrees, it is the right place. However, the start of the video is then from the beginning of the video and not from the place with the time indication.

Here is an example:

https://youtu.be/4ZvLE2CAVMM?t=74m44s

Regards
Hobokens

**Comment by heisenbol** [comment]
This is resolved in version 1.3.0. A new option is added to set the time index to start the playback. Specified in seconds

**Comment by Hobokens** [comment]
Thanks a lot for the quick support.
Have a nice day!
Hobokens
