### ISSUE TITLE
skvideo does not contain a composer.json

### ISSUE THREAD

**Issue by CarstenHager** [sksksksk/skvideo#9]
In future versions of TYPO3, it will be mandatory for extensions to provide a composer.json file. This will be needed to identify an extension and works as a replacement for the ext_emconf.php. Therefore, the composer.json file must also include the extension key under "extra > typo3/cms > extension-key". Please add a composer.json, including the extension-key property, in the corresponding extension folder. You can use the auto-generated proposal below and update the composer.json file extension. 

Auto-generated composer.json Please verify its contents, adjust it to your needs and and put it into typo3conf/ext/skvideo/composer.json. 

`{
    "name": "typo3-local/skvideo",
    "description": " - ",
    "license": "GPL-2.0-or-later",
    "type": "typo3-cms-extension",
    "authors": [
        {
            "name": "",
            "email": "no-email@given.com"
        }
    ],
    "require": [],
    "suggest": [],
    "conflict": [],
    "extra": {
        "typo3/cms": {
            "extension-key": "skvideo"
        }
    },
    "version": "dev-local",
    "autoload": {
        "classmap": [
            "*"
        ]
    }
}`

**Comment by heisenbol** [comment]
Carsten, thanks for this. I actually have the whole issue with a Packagist distribution on my todo list. I'll try to resolve this with the TYPO3 11 compatible version within the next few weeks.

**Comment by heisenbol** [comment]
Version 1.4.1 includes now a composer.json. I will upload it to TER within the next days
